In [398]:
import pandas as pd

In [399]:
df = pd.read_csv('dados_extraidos_ambos_livros.csv')
df.drop(columns=['formacao'], inplace=True)
df

,titulo,descricao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu..."
1,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...
2,0103-05 Praça da aeronáutica - Cabo; Primeiro-...,Estão compreendidas nesta família ocupacional ...
3,0201-05 Coronel da Polícia Militar \n0201-10...,Comandam unidades de Polícia Militar e elabora...
4,0202-05 Capitão da Polícia Militar,"Comandam operações de polícia ostensiva, plane..."
...,...,...
601,9911-05 Conservador de via permanente (trilhos...,"Analisam o veículo a ser reparado, realizam o ..."
602,9912-05 Mantenedor de equipamentos de parques ...,"Realizam manutenção de equipamentos, montagem ..."
603,9913-05 Funileiro de veículos (reparação) - Ch...,"Realizam manutenção geral em vias, manejam áre..."
604,9921-05 Alinhador de pneus\n9921-10 Balanceado...,NaN
605,9922-05 Encarregado geral de operações de cons...,NaN

In [400]:
desc_alinhador_pneus = 'Realizam manutenção de equipamentos, montagem e desmontagem de pneu e alinhamento. Controlam vida útil e utilização do pneu. Trocam e ressulcam pneus. Consertam pneus a frio e a quente, reparam câmara de ar e balanceiam conjunto de roda e pneu. Prestam socorro a veículos e lavam chassi e peças. Trabalham seguindo normas de segurança, higiene, qualidade e proteção ao meio ambiente.'

desc_encarregado_geral = 'Realizam manutenção geral em vias, manejam áreas verdes, tapam buracos, limpam vias permanentes e conservam bueiros e galerias de águas pluviais. Recompõem aterros e recuperam obras de arte. Controlam atividades de conservação e trabalham seguindo normas de segurança, higiene, qualidade e proteção ao meio ambiente.'

if pd.isna(df.loc[604, 'descricao']):
    df.loc[604, 'descricao'] = desc_alinhador_pneus

if pd.isna(df.loc[605, 'descricao']):
    df.loc[605, 'descricao'] = desc_encarregado_geral

In [401]:
df

,titulo,descricao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu..."
1,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...
2,0103-05 Praça da aeronáutica - Cabo; Primeiro-...,Estão compreendidas nesta família ocupacional ...
3,0201-05 Coronel da Polícia Militar \n0201-10...,Comandam unidades de Polícia Militar e elabora...
4,0202-05 Capitão da Polícia Militar,"Comandam operações de polícia ostensiva, plane..."
...,...,...
601,9911-05 Conservador de via permanente (trilhos...,"Analisam o veículo a ser reparado, realizam o ..."
602,9912-05 Mantenedor de equipamentos de parques ...,"Realizam manutenção de equipamentos, montagem ..."
603,9913-05 Funileiro de veículos (reparação) - Ch...,"Realizam manutenção geral em vias, manejam áre..."
604,9921-05 Alinhador de pneus\n9921-10 Balanceado...,"Realizam manutenção de equipamentos, montagem ..."
605,9922-05 Encarregado geral de operações de cons...,"Realizam manutenção geral em vias, manejam áre..."

In [402]:
import re

def descompactar_cargos(df):
    """
    Descompacta ocupações que estão em uma única linha, separadas por \n
    Mantém alinhamento entre título e descrição
    """
    rows = []
    
    for idx, row in df.iterrows():
        titulo = str(row['titulo']).strip()
        descricao = str(row['descricao']).strip()
        
        # Divide títulos por quebra de linha
        titulos_lista = [t.strip() for t in titulo.split('\n') if t.strip()]
        
        # Se houver múltiplos títulos, divide a descrição também (ou repete)
        if len(titulos_lista) > 1:
            # Tenta dividir a descrição por padrão de código ou usa a mesma para todos
            descricoes_lista = descricao.split('\n') if '\n' in descricao else [descricao] * len(titulos_lista)
            
            # Se números de itens não baterem, repete a última descrição
            while len(descricoes_lista) < len(titulos_lista):
                descricoes_lista.append(descricoes_lista[-1] if descricoes_lista else descricao)
        else:
            titulos_lista = [titulo]
            descricoes_lista = [descricao]
        
        # Cria uma linha para cada título
        for t, d in zip(titulos_lista, descricoes_lista):
            rows.append({'titulo': t.strip(), 'descricao': d.strip()})
    
    return pd.DataFrame(rows)

# Aplica a descompactação
df_descompactado = descompactar_cargos(df)

df_descompactado.info()

<class 'pandas.DataFrame'>
RangeIndex: 5218 entries, 0 to 5217
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     5218 non-null   str
 1   descricao  5218 non-null   str
dtypes: str(2)
memory usage: 767.4 KB

In [403]:
df

,titulo,descricao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu..."
1,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...
2,0103-05 Praça da aeronáutica - Cabo; Primeiro-...,Estão compreendidas nesta família ocupacional ...
3,0201-05 Coronel da Polícia Militar \n0201-10...,Comandam unidades de Polícia Militar e elabora...
4,0202-05 Capitão da Polícia Militar,"Comandam operações de polícia ostensiva, plane..."
...,...,...
601,9911-05 Conservador de via permanente (trilhos...,"Analisam o veículo a ser reparado, realizam o ..."
602,9912-05 Mantenedor de equipamentos de parques ...,"Realizam manutenção de equipamentos, montagem ..."
603,9913-05 Funileiro de veículos (reparação) - Ch...,"Realizam manutenção geral em vias, manejam áre..."
604,9921-05 Alinhador de pneus\n9921-10 Balanceado...,"Realizam manutenção de equipamentos, montagem ..."
605,9922-05 Encarregado geral de operações de cons...,"Realizam manutenção geral em vias, manejam áre..."

In [404]:
def descompactar_descricoes_correto(df):
    """
    Descompacta títulos que estão em uma única linha com \n
    Separa ocupações pelo padrão NNNN-NN (CBO code)
    Mantém a mesma descrição para todas as ocupações do mesmo grupo
    Remove quebras de linha da descrição (normaliza espaços)
    """
    import re
    rows = []
    
    for idx, row in df.iterrows():
        titulo = str(row['titulo']).strip()
        descricao = str(row['descricao']).strip()
        
        # Se descricao for 'nan', deixa vazia
        if descricao.lower() == 'nan':
            descricao = ''
        else:
            # Remove quebras de linha da descrição e normaliza espaços
            descricao = ' '.join(descricao.split())
        
        # Separa ocupações pelo padrão NNNN-NN (CBO code no início)
        # Encontra todos os matches de "NNNN-NN" seguidos de tudo até o próximo NNNN-NN ou fim
        ocupacoes = []
        
        # Primeiro, substitui \n por espaço para normalizar
        titulo_normalizado = ' '.join(titulo.split('\n'))
        
        # Padrão: NNNN-NN no início seguido de resto até o próximo NNNN-NN
        padrao = r'(\d{4}-\d{2}[^\d]*?)(?=\d{4}-\d{2}|$)'
        matches = re.findall(padrao, titulo_normalizado)
        
        if matches:
            ocupacoes = [m.strip() for m in matches if m.strip()]
        else:
            # Se não encontrar padrão, usa a string inteira
            ocupacoes = [titulo]
        
        # Cria uma linha para cada ocupação com a mesma descrição
        for ocupacao in ocupacoes:
            rows.append({
                'titulo': ocupacao,
                'descricao': descricao
            })
    
    return pd.DataFrame(rows)

# Aplica a descompactação
df_descompactado = descompactar_descricoes_correto(df)

df_descompactado.info()

<class 'pandas.DataFrame'>
RangeIndex: 2486 entries, 0 to 2485
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2486 non-null   str
 1   descricao  2486 non-null   str
dtypes: str(2)
memory usage: 1.4 MB

In [405]:
df_descompactado.tail()

,titulo,descricao
2481,9922-05 Encarregado geral de operações de cons...,"Realizam manutenção geral em vias, manejam áre..."
2482,9922-10 Encarregado de equipe de conservação d...,"Realizam manutenção geral em vias, manejam áre..."
2483,9922-15 Operador de ceifadeira na conservação ...,"Realizam manutenção geral em vias, manejam áre..."
2484,9922-20 Pedreiro de conservação de vias perman...,"Realizam manutenção geral em vias, manejam áre..."
2485,9922-25 Auxiliar geral de conservação de vias ...,"Realizam manutenção geral em vias, manejam áre..."

In [406]:
# Verificar quantas linhas têm descrição vazia
vazias = df_descompactado[df_descompactado['descricao'] == '']
print(f"Total de linhas SEM descrição: {len(vazias)} ({len(vazias)/len(df_descompactado)*100:.1f}%)")
print(f"\nExemplos de códigos sem descrição:")
print(vazias.head(20))

Total de linhas SEM descrição: 0 (0.0%)

Exemplos de códigos sem descrição:
Empty DataFrame
Columns: [titulo, descricao]
Index: []

In [407]:

df_descompactado.loc[df_descompactado['titulo'].str.contains('9921-', regex=False, na=False), 'descricao'] = desc_alinhador_pneus

df_descompactado.loc[df_descompactado['titulo'].str.contains('9922-', regex=False, na=False), 'descricao'] = desc_encarregado_geral

# Verificar se ficou tudo preenchido
vazias_agora = df_descompactado[df_descompactado['descricao'] == '']
print(f"Linhas SEM descrição agora: {len(vazias_agora)}")
print(f"\nExemplos com descrição preenchida:")
print(df_descompactado.loc[df_descompactado['titulo'].str.contains('9921-|9922-', regex=True, na=False)].head(15))

Linhas SEM descrição agora: 0

Exemplos com descrição preenchida:
                                                 titulo  \
2477                         9921-05 Alinhador de pneus
2478                                9921-10 Balanceador
2479  9921-15 Borracheiro - Borracheiro auxiliar; Co...
2480                           9921-20 Lavador de peças
2481  9922-05 Encarregado geral de operações de cons...
2482  9922-10 Encarregado de equipe de conservação d...
2483  9922-15 Operador de ceifadeira na conservação ...
2484  9922-20 Pedreiro de conservação de vias perman...
2485  9922-25 Auxiliar geral de conservação de vias ...

                                              descricao
2477  Realizam manutenção de equipamentos, montagem ...
2478  Realizam manutenção de equipamentos, montagem ...
2479  Realizam manutenção de equipamentos, montagem ...
2480  Realizam manutenção de equipamentos, montagem ...
2481  Realizam manutenção geral em vias, manejam áre...
2482  Realizam manutenção geral em vias, manejam áre...
2483  Realizam manutenção geral em vias, manejam áre...
2484  Realizam manutenção geral em vias, manejam áre...
2485  Realizam manutenção geral em vias, manejam áre...

In [408]:
df_descompactado

,titulo,descricao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu..."
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu..."
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu..."
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...
...,...,...
2481,9922-05 Encarregado geral de operações de cons...,"Realizam manutenção geral em vias, manejam áre..."
2482,9922-10 Encarregado de equipe de conservação d...,"Realizam manutenção geral em vias, manejam áre..."
2483,9922-15 Operador de ceifadeira na conservação ...,"Realizam manutenção geral em vias, manejam áre..."
2484,9922-20 Pedreiro de conservação de vias perman...,"Realizam manutenção geral em vias, manejam áre..."
2485,9922-25 Auxiliar geral de conservação de vias ...,"Realizam manutenção geral em vias, manejam áre..."

In [409]:
# Versão correta: gera lista_4n com base no df_descompactado
lista_4n = (
    df_descompactado['titulo']
    .astype(str)
    .str.extract(r'^(\d{4})')[0]
    .fillna('')
    .tolist()
)

df_descompactado['4n'] = lista_4n

print(f"Tamanho lista_4n: {len(lista_4n)}")
print(f"Tamanho df_descompactado: {len(df_descompactado)}")
print(df_descompactado[['titulo', '4n']].head(10))

Tamanho lista_4n: 2486
Tamanho df_descompactado: 2486
                                              titulo    4n
0  0101-05 Oficial General da Aeronáutica - Briga...  0101
1  0101-10 Oficial General do Exército - General-...  0101
2  0101-15 Oficial General da Marinha - Almirante...  0101
3  0102-05 Oficial da Aeronáutica - Capitão; Coro...  0102
4  0102-10 Oficial do Exército - Capitão; Coronel...  0102
5  0102-15 Oficial da Marinha - Capitão-de-corvet...  0102
6  0103-05 Praça da aeronáutica - Cabo; Primeiro-...  0103
7  0103-10 Praça do exército - Cabo; Primeiro-sar...  0103
8  0103-15 Praça da marinha - Cabo; Marinheiro; P...  0103
9                 0201-05 Coronel da Polícia Militar  0201

In [410]:
df_descompactado

,titulo,descricao,4n
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",0101
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",0101
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",0101
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,0102
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,0102
...,...,...,...
2481,9922-05 Encarregado geral de operações de cons...,"Realizam manutenção geral em vias, manejam áre...",9922
2482,9922-10 Encarregado de equipe de conservação d...,"Realizam manutenção geral em vias, manejam áre...",9922
2483,9922-15 Operador de ceifadeira na conservação ...,"Realizam manutenção geral em vias, manejam áre...",9922
2484,9922-20 Pedreiro de conservação de vias perman...,"Realizam manutenção geral em vias, manejam áre...",9922
2485,9922-25 Auxiliar geral de conservação de vias ...,"Realizam manutenção geral em vias, manejam áre...",9922

In [411]:
dados_nossos = pd.read_excel('dados_nossos.xlsx')
dados_nossos.columns

Index(['CODIGO', 'Grupo', 'TITULO', 'Tarefa'], dtype='str')

In [412]:
dados_nossos['Grupo'] = dados_nossos['Grupo'].astype(str).str.zfill(4)
dados_nossos

,CODIGO,Grupo,TITULO,Tarefa
0,10105,0101,Oficial general da aeronáutica,Abstrata
1,10110,0101,Oficial general do exército,Abstrata
2,10115,0101,Oficial general da marinha,Abstrata
3,10205,0102,Oficial da aeronáutica,Abstrata
4,10210,0102,Oficial do exército,Abstrata
...,...,...,...,...
2720,992205,9922,Encarregado geral de operações de conservação ...,Manual
2721,992210,9922,Encarregado de equipe de conservação de vias p...,Manual
2722,992215,9922,Operador de ceifadeira na conservação de vias ...,Manual
2723,992220,9922,Pedreiro de conservação de vias permanentes (e...,Manual
2724,992225,9922,Auxiliar geral de conservação de vias permanen...,Manual

In [413]:
dados_nossos['CODIGO'] = dados_nossos['CODIGO'].astype(str).str.zfill(6)
dados_nossos.head(30)

    CODIGO Grupo                                 TITULO    Tarefa
0   010105  0101         Oficial general da aeronáutica  Abstrata
1   010110  0101            Oficial general do exército  Abstrata
2   010115  0101             Oficial general da marinha  Abstrata
3   010205  0102                 Oficial da aeronáutica  Abstrata
4   010210  0102                    Oficial do exército  Abstrata
5   010215  0102                     Oficial da marinha  Abstrata
6   010305  0103                   Praça da aeronáutica  Abstrata
7   010310  0103                      Praça do exército  Abstrata
8   010315  0103                       Praça da marinha  Abstrata
9   020105  0201             Coronel da polícia militar  Abstrata
10  020110  0201     Tenente-coronel da polícia militar  Abstrata
11  020115  0201               Major da polícia militar  Abstrata
12  020205  0202             Capitão da polícia militar  Abstrata
13  020305  0203    Primeiro tenente de polícia militar  Abstrata
14  020310  0203     Segundo tenente de polícia militar  Abstrata
15  021105  0211          Subtenente da policia militar  Abstrata
16  021110  0211            Sargento da policia militar  Abstrata
17  021205  0212                Cabo da polícia militar  Abstrata
18  021210  0212             Soldado da polícia militar  Abstrata
19  030105  0301               Coronel bombeiro militar  Abstrata
20  030110  0301                 Major bombeiro militar  Abstrata
21  030115  0301       Tenente-coronel bombeiro militar  Abstrata
22  030205  0302               Capitão bombeiro militar  Abstrata
23  030305  0303  Tenente do corpo de bombeiros militar  Abstrata
24  031105  0311            Subtenente bombeiro militar  Abstrata
25  031110  0311              Sargento bombeiro militar  Abstrata
26  031205  0312                  Cabo bombeiro militar  Abstrata
27  031210  0312               Soldado bombeiro militar  Abstrata
28  111105  1111                                Senador  Abstrata
29  111110  1111                       Deputado federal  Abstrata

In [414]:
lista_não_tem = []
for idx, row in dados_nossos.iterrows():
    if row['Grupo'] not in df_descompactado['4n'].values:
        lista_não_tem.append(row['Grupo'])
não_tem = pd.DataFrame(lista_não_tem, columns=['Grupos não encontrados no CBO descompactado'])

In [415]:
dados_nossos.info()

<class 'pandas.DataFrame'>
RangeIndex: 2725 entries, 0 to 2724
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CODIGO  2725 non-null   str
 1   Grupo   2725 non-null   str
 2   TITULO  2725 non-null   str
 3   Tarefa  2725 non-null   str
dtypes: str(4)
memory usage: 220.2 KB

In [416]:
for idx, row in dados_nossos.iterrows():
    if row['CODIGO'][:4] == '3030':
        row.CODIGO = '030305'

In [417]:
dados_faltando = pd.read_excel('dados_nossos.xlsx', sheet_name='n+tem_planilha')
dados_faltando.reset_index(inplace=True, drop=True)
dados_faltando = dados_faltando.rename(columns={'Ocupações que estão nos grupos': 'titulo'})
dados_faltando = dados_faltando.rename(columns={'Descrição Sumária': 'descricao'})

dados_faltando

,Grupos que não estão nos livros:,titulo,descrição da família,descricao
0,1418,1418-05 Gerente de administração em aeroportos...,Gerentes operacionais da aviação civil,Planejam e gerenciam atividades de operação da...
1,2251,2251-03 Médico infectologista\n2251-05 Médico ...,Médicos clínicos,Realizam consultas e atendimentos médicos; tra...
2,2252,225203 Médico em cirurgia vascular \n225210 Mé...,Médicos em especialidades cirúrgicas,Realizam intervenções cirúrgicas de acordo com...
3,2253,225305 Médico citopatologista \n225310 Médico ...,Médicos em medicina diagnóstica e terapêutica,Realizam procedimentos de diagnóstico e terapê...
4,2261,2261-05 Quiropraxista \n2261-10 Osteopata,Osteopatas e quiropraxistas,Tratam e atendem pacientes e clientes aplicand...
5,2263,2263-05 Musicoterapeuta 2263-10 Arteterapeuta ...,"Profissionais das terapias criativas,equoteráp...","Realizam atendimento terapêutico em pacientes,..."
6,2414,2414-05 Conselheiro Julgador,Conselheiros julgadores,Relatam de forma detalhada os recursos de proc...
7,2429,2429-05 Oficial de inteligência 2429-10 Oficia...,Profissionais da inteligência,"Atuam no planejamento, execução, coordenação, ..."
8,2527,2527-05 Analista de pcp (programação e control...,"Profissionais de planejamento, programação e c...",Planejam processos produtivos e logísticos def...
9,2534,2534-05 Analista de mídias sociais 2534-10 Inf...,Profissionais de mídias digitais e afins,"Realizam gestão das redes sociais, monitorando..."
10,2545,2545-05 Fiscal de atividades urbanas,Profissionais da fiscalização de atividades ur...,"Realizam vistorias e fiscalizações,lavram auto..."
11,2619,2619-05 Continuista 2619-10 Assistente de dire...,Assistentes de direção (tv) e continuístas,Colaboram na pré-produção de programas e conte...
12,3148,3148-05 Inspetor de equipamentos\n3148-10 Insp...,Especialistas em inspeções industriais,"Atuam nas fases de construção, montagem e oper..."
13,3227,3227-05 Técnico em acupuntura \n3227-10 Técnic...,Técnicos e profissionais em práticas integrati...,Aplicam procedimentos de práticas integrativas...
14,3519,3519-05 Agente de inteligência \n3519-10 Agent...,Técnicos da inteligência,"Oferecem suporte no planejamento, execução, su..."
15,4153,4153-05 Registrador de câncer \n4153-10 Analis...,Trabalhadores em registros e informações em saúde,Coletam e registram dados clínicos dos pacient...
16,4242,"4242-05 Coordenador de provas (concurso, avali...",Aplicadores de provas e afins,"Aplicam provas (concurso, avaliação e exame), ..."
17,5115,5115-05 Condutor de turismo de aventura 5115-1...,Condutores de turismo,Conduzem clientes/pessoas nas atividades de pa...
18,5169,5169-05 Tatuador \n5169-10 Micropigmentador \n...,Trabalhadores nos serviços de arte corporal,Realizam a dermopigmentação e perfuração corpo...
19,7911,7911-05 Artesão bordador \n7911-10 Artesão cer...,Artesãos,Os profissionais desta família ocupacional cri...

In [418]:
dados_faltando = descompactar_descricoes_correto(dados_faltando)

In [419]:
dados = pd.concat([df_descompactado, dados_faltando], ignore_index=True)
dados

,titulo,descricao,4n
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",0101
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",0101
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",0101
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,0102
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,0102
...,...,...,...
2578,7911-30 Artesão escultor,Os profissionais desta família ocupacional cri...,NaN
2579,7911-35 Artesão moveleiro (exceto reciclado),Os profissionais desta família ocupacional cri...,NaN
2580,7911-40 Artesão tecelão,Os profissionais desta família ocupacional cri...,NaN
2581,7911-45 Artesão trançador,Os profissionais desta família ocupacional cri...,NaN
2582,7911-50 Artesão crocheteiro,Os profissionais desta família ocupacional cri...,NaN

In [420]:
dados['ocupacao'] = dados['titulo'].str.extract(r'(\d{4}-\d{2})')[0]
dados['ocupacao'] = dados['ocupacao'].str.replace('-', '', regex=False)

In [421]:
dados

,titulo,descricao,4n,ocupacao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",0101,010105
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",0101,010110
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",0101,010115
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,0102,010205
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,0102,010210
...,...,...,...,...
2578,7911-30 Artesão escultor,Os profissionais desta família ocupacional cri...,NaN,791130
2579,7911-35 Artesão moveleiro (exceto reciclado),Os profissionais desta família ocupacional cri...,NaN,791135
2580,7911-40 Artesão tecelão,Os profissionais desta família ocupacional cri...,NaN,791140
2581,7911-45 Artesão trançador,Os profissionais desta família ocupacional cri...,NaN,791145
2582,7911-50 Artesão crocheteiro,Os profissionais desta família ocupacional cri...,NaN,791150

In [422]:
index = dados['ocupacao'].isna()
dados[index]

,titulo,descricao,4n,ocupacao
2524,225203 Médico em cirurgia vascular \n225210 Mé...,Realizam intervenções cirúrgicas de acordo com...,NaN,NaN
2525,225305 Médico citopatologista \n225310 Médico ...,Realizam procedimentos de diagnóstico e terapê...,NaN,NaN

In [423]:
# Descompactar linhas com padrão NNNNNN (sem hífen)
def descompactar_sem_hifen(texto, descricao):
    """
    Descompacta ocupações com padrão NNNNNN (6 dígitos sem hífen)
    """
    import re
    
    # Normaliza quebras de linha em espaços
    texto_normalizado = ' '.join(texto.split('\n'))
    
    # Padrão: 6 dígitos seguidos de resto até próximos 6 dígitos ou fim
    padrao = r'(\d{6}[^\d]*?)(?=\d{6}|$)'
    matches = re.findall(padrao, texto_normalizado)
    
    if matches:
        ocupacoes = [m.strip() for m in matches if m.strip()]
    else:
        ocupacoes = [texto]
    
    # Normaliza descrição
    descricao_normalizada = ' '.join(str(descricao).split())
    
    return [{
        'titulo': ocp,
        'descricao': descricao_normalizada
    } for ocp in ocupacoes]

# Pegar as linhas com NaN e descompactar
linhas_nan = dados[dados['ocupacao'].isna()].copy()

linhas_descompactadas = []
for idx, row in linhas_nan.iterrows():
    linhas_descompactadas.extend(
        descompactar_sem_hifen(row['titulo'], row['descricao'])
    )

# Criar DataFrame com linhas descompactadas
df_novas = pd.DataFrame(linhas_descompactadas)

# Adicionar coluna 'ocupacao' para as novas linhas (formato NNNNNN sem hífen)
df_novas['ocupacao'] = df_novas['titulo'].str.extract(r'(\d{6})')[0]

print(f"Linhas descompactadas: {len(df_novas)}")
print("\nNovas linhas:")
df_novas

Linhas descompactadas: 29

Novas linhas:

,titulo,descricao,ocupacao
0,225203 Médico em cirurgia vascular,Realizam intervenções cirúrgicas de acordo com...,225203
1,225210 Médico cirurgião cardiovascular,Realizam intervenções cirúrgicas de acordo com...,225210
2,225215 Médico cirurgião de cabeça e pescoço,Realizam intervenções cirúrgicas de acordo com...,225215
3,225220 Médico cirurgião do aparelho digestivo,Realizam intervenções cirúrgicas de acordo com...,225220
4,225225 Médico cirurgião geral,Realizam intervenções cirúrgicas de acordo com...,225225
5,225230 Médico cirurgião pediátrico,Realizam intervenções cirúrgicas de acordo com...,225230
6,225235 Médico cirurgião plástico,Realizam intervenções cirúrgicas de acordo com...,225235
7,225240 Médico cirurgião torácico,Realizam intervenções cirúrgicas de acordo com...,225240
8,225250 Médico ginecologista e obstetra,Realizam intervenções cirúrgicas de acordo com...,225250
9,225255 Médico mastologista,Realizam intervenções cirúrgicas de acordo com...,225255
10,225260 Médico neurocirurgião,Realizam intervenções cirúrgicas de acordo com...,225260
11,225265 Médico oftalmologista,Realizam intervenções cirúrgicas de acordo com...,225265
12,225270 Médico ortopedista e traumatologista,Realizam intervenções cirúrgicas de acordo com...,225270
13,225275 Médico otorrinolaringologista,Realizam intervenções cirúrgicas de acordo com...,225275
14,225280 Médico coloproctologista,Realizam intervenções cirúrgicas de acordo com...,225280
15,225285 Médico urologista,Realizam intervenções cirúrgicas de acordo com...,225285
16,225290 Médico cancerologista cirurgíco,Realizam intervenções cirúrgicas de acordo com...,225290
17,225295 Médico cirurgião da mão,Realizam intervenções cirúrgicas de acordo com...,225295
18,225305 Médico citopatologista,Realizam procedimentos de diagnóstico e terapê...,225305
19,225310 Médico em endoscopia,Realizam procedimentos de diagnóstico e terapê...,225310
20,225315 Médico em medicina nuclear,Realizam procedimentos de diagnóstico e terapê...,225315
21,225320 Médico em radiologia e diagnóstico por ...,Realizam procedimentos de diagnóstico e terapê...,225320
22,225325 Médico patologista,Realizam procedimentos de diagnóstico e terapê...,225325
23,225330 Médico radioterapeuta,Realizam procedimentos de diagnóstico e terapê...,225330
24,225335 Médico patologista clínico / medicina l...,Realizam procedimentos de diagnóstico e terapê...,225335
25,225340 Médico hemoterapeuta,Realizam procedimentos de diagnóstico e terapê...,225340
26,225345 Médico hiperbarista,Realizam procedimentos de diagnóstico e terapê...,225345
27,225350 Médico neurofisiologista clínico,Realizam procedimentos de diagnóstico e terapê...,225350
28,225355 Médico radiologista intervencionista,Realizam procedimentos de diagnóstico e terapê...,225355

In [424]:
dados = pd.concat([dados, df_novas], ignore_index=True)

In [425]:
dados.dropna(subset=['ocupacao'], inplace=True)
dados.info()

<class 'pandas.DataFrame'>
Index: 2610 entries, 0 to 2611
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2610 non-null   str
 1   descricao  2610 non-null   str
 2   4n         2486 non-null   str
 3   ocupacao   2610 non-null   str
dtypes: str(4)
memory usage: 1.6 MB

In [426]:
dados

,titulo,descricao,4n,ocupacao
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",0101,010105
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",0101,010110
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",0101,010115
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,0102,010205
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,0102,010210
...,...,...,...,...
2607,225335 Médico patologista clínico / medicina l...,Realizam procedimentos de diagnóstico e terapê...,NaN,225335
2608,225340 Médico hemoterapeuta,Realizam procedimentos de diagnóstico e terapê...,NaN,225340
2609,225345 Médico hiperbarista,Realizam procedimentos de diagnóstico e terapê...,NaN,225345
2610,225350 Médico neurofisiologista clínico,Realizam procedimentos de diagnóstico e terapê...,NaN,225350
2611,225355 Médico radiologista intervencionista,Realizam procedimentos de diagnóstico e terapê...,NaN,225355

In [427]:
lista_não_tem = []

for idx, row in dados_nossos.iterrows():
    if row['CODIGO'] not in dados['ocupacao'].values:
        lista_não_tem.append(row['CODIGO'])

In [428]:
lista_não_tem_df = pd.DataFrame(lista_não_tem, columns=['ocupacao'])
lista_não_tem_df.value_counts().sum()

np.int64(200)

In [429]:
lista_não_tem_df

    ocupacao
0     111345
1     122520
2     131215
3     131220
4     131225
..       ...
195   791160
196   862160
197   913125
198   951315
199   951320

[200 rows x 1 columns]

In [430]:
dados_nossos

,CODIGO,Grupo,TITULO,Tarefa
0,010105,0101,Oficial general da aeronáutica,Abstrata
1,010110,0101,Oficial general do exército,Abstrata
2,010115,0101,Oficial general da marinha,Abstrata
3,010205,0102,Oficial da aeronáutica,Abstrata
4,010210,0102,Oficial do exército,Abstrata
...,...,...,...,...
2720,992205,9922,Encarregado geral de operações de conservação ...,Manual
2721,992210,9922,Encarregado de equipe de conservação de vias p...,Manual
2722,992215,9922,Operador de ceifadeira na conservação de vias ...,Manual
2723,992220,9922,Pedreiro de conservação de vias permanentes (e...,Manual
2724,992225,9922,Auxiliar geral de conservação de vias permanen...,Manual

In [431]:
codigo_col = 'ocupacao'

lista_não_tem_df[codigo_col] = lista_não_tem_df[codigo_col].astype(str).str.zfill(6)

tarefa_por_codigo = dados_nossos.set_index('CODIGO')['Tarefa']
titulo_por_codigo = dados_nossos.set_index('CODIGO')['TITULO']


lista_não_tem_df['tarefa'] = lista_não_tem_df[codigo_col].map(tarefa_por_codigo)
lista_não_tem_df['titulo'] = lista_não_tem_df[codigo_col].map(titulo_por_codigo)
lista_não_tem_df.head()

  ocupacao    tarefa                          titulo
0   111345  Abstrato                Juiz do trabalho
1   122520  Abstrata                     Turismólogo
2   131215  Abstrata  Tecnólogo em gestão hospitalar
3   131220  Abstrata                     Gerontólogo
4   131225  Abstrata                     Sanitarista

In [432]:
# Criar coluna descricao em lista_não_tem_df com base no Grupo (4 primeiros dígitos)
lista_não_tem_df['grupo_4d'] = lista_não_tem_df['ocupacao'].astype(str).str[:4]

# Mapeamento Grupo -> Tarefa (usado como descrição)
# Quando há mais de uma tarefa no mesmo grupo, usa a mais frequente
descricao_por_grupo = (
    dados_nossos.groupby('Grupo')['Tarefa']
    .agg(lambda s: s.mode().iat[0] if not s.mode().empty else s.dropna().iat[0] if not s.dropna().empty else '')
)

lista_não_tem_df['descricao'] = lista_não_tem_df['grupo_4d'].map(descricao_por_grupo).fillna('')

# (opcional) remover coluna auxiliar
lista_não_tem_df.drop(columns=['grupo_4d'], inplace=True)

print('Coluna descricao criada com sucesso.')
print(lista_não_tem_df[['ocupacao', 'titulo', 'tarefa', 'descricao']].head(15))
print('\nDescrições vazias:', (lista_não_tem_df['descricao'] == '').sum())

Coluna descricao criada com sucesso.
   ocupacao                                             titulo    tarefa  \
0    111345                                   Juiz do trabalho  Abstrato
1    122520                                        Turismólogo  Abstrata
2    131215                     Tecnólogo em gestão hospitalar  Abstrata
3    131220                                        Gerontólogo  Abstrata
4    131225                                        Sanitarista  Abstrata
5    141410                              Comerciante varejista  Abstrata
6    142125                             Analista de compliance  Abstrata
7    142130                                 Analista de riscos  Abstrata
8    142135        Oficial de proteção de dados pessoais (dpo)  Abstrata
9    142140                Profissional de facility management  Abstrato
10   142325                                  Relações públicas  Abstrata
11   142330                               Analista de negócios  Abstrata
12   142335                    Analista de pesquisa de mercado  Abstrata
13   142340                                            Ouvidor  Abstrata
14   142345  Profissional de relações institucionais e gove...  Abstrata

   descricao
0   Abstrato
1   Abstrata
2   Abstrata
3   Abstrata
4   Abstrata
5   Abstrata
6   Abstrata
7   Abstrata
8   Abstrata
9   Abstrata
10  Abstrata
11  Abstrata
12  Abstrata
13  Abstrata
14  Abstrata

Descrições vazias: 0

In [433]:
lista_não_tem_df

,ocupacao,tarefa,titulo,descricao
0,111345,Abstrato,Juiz do trabalho,Abstrato
1,122520,Abstrata,Turismólogo,Abstrata
2,131215,Abstrata,Tecnólogo em gestão hospitalar,Abstrata
3,131220,Abstrata,Gerontólogo,Abstrata
4,131225,Abstrata,Sanitarista,Abstrata
...,...,...,...,...
195,791160,R. Manual,Artesão rendeiro,R. Manual
196,862160,R. Manual,Operador de abastecimento de combustível de ae...,R. Manual
197,913125,R. Manual,Vulcanizador de correias transportadoras,Manual
198,951315,Manual,Monitor de sistemas eletrônicos de segurança i...,Manual
199,951320,Manual,Monitor de sistemas eletrônicos de segurança e...,Manual

In [434]:
# Corrigir: usar descricao do dataframe `dados` (não de `dados_nossos`)
lista_não_tem_df['grupo_4d'] = lista_não_tem_df['ocupacao'].astype(str).str.zfill(6).str[:4]

dados_aux = dados.copy()
dados_aux['ocupacao'] = dados_aux['ocupacao'].astype(str).str.zfill(6)
dados_aux['grupo_4d'] = dados_aux['ocupacao'].str[:4]
dados_aux['descricao'] = dados_aux['descricao'].astype(str).str.strip()

descricao_por_grupo_dados = (
    dados_aux[dados_aux['descricao'].ne('')]
    .groupby('grupo_4d')['descricao']
    .agg(lambda s: s.mode().iat[0] if not s.mode().empty else s.iloc[0])
)

lista_não_tem_df['descricao'] = lista_não_tem_df['grupo_4d'].map(descricao_por_grupo_dados).fillna('')
lista_não_tem_df.drop(columns=['grupo_4d'], inplace=True)

print('Descrição atualizada usando `dados`.')
print(lista_não_tem_df[['ocupacao', 'titulo', 'descricao']].head(15))
print('\nDescrições vazias:', (lista_não_tem_df['descricao'] == '').sum())

Descrição atualizada usando `dados`.
   ocupacao                                             titulo  \
0    111345                                   Juiz do trabalho
1    122520                                        Turismólogo
2    131215                     Tecnólogo em gestão hospitalar
3    131220                                        Gerontólogo
4    131225                                        Sanitarista
5    141410                              Comerciante varejista
6    142125                             Analista de compliance
7    142130                                 Analista de riscos
8    142135        Oficial de proteção de dados pessoais (dpo)
9    142140                Profissional de facility management
10   142325                                  Relações públicas
11   142330                               Analista de negócios
12   142335                    Analista de pesquisa de mercado
13   142340                                            Ouvidor
14   142345  Profissional de relações institucionais e gove...

                                            descricao
0   Decidem conflitos individuais e coletivos em n...
1   Dirigem, no mais alto nível, e como representa...
2   Planejam, coordenam e avaliam ações de saúde; ...
3   Planejam, coordenam e avaliam ações de saúde; ...
4   Planejam, coordenam e avaliam ações de saúde; ...
5   Planejam atividades nos comércios varejista, a...
6   Exercem a gerência dos serviços administrativo...
7   Exercem a gerência dos serviços administrativo...
8   Exercem a gerência dos serviços administrativo...
9   Exercem a gerência dos serviços administrativo...
10  Elaboram planos estratégicos das áreas de come...
11  Elaboram planos estratégicos das áreas de come...
12  Elaboram planos estratégicos das áreas de come...
13  Elaboram planos estratégicos das áreas de come...
14  Elaboram planos estratégicos das áreas de come...

Descrições vazias: 0

In [435]:
lista_não_tem_df

,ocupacao,tarefa,titulo,descricao
0,111345,Abstrato,Juiz do trabalho,Decidem conflitos individuais e coletivos em n...
1,122520,Abstrata,Turismólogo,"Dirigem, no mais alto nível, e como representa..."
2,131215,Abstrata,Tecnólogo em gestão hospitalar,"Planejam, coordenam e avaliam ações de saúde; ..."
3,131220,Abstrata,Gerontólogo,"Planejam, coordenam e avaliam ações de saúde; ..."
4,131225,Abstrata,Sanitarista,"Planejam, coordenam e avaliam ações de saúde; ..."
...,...,...,...,...
195,791160,R. Manual,Artesão rendeiro,Os profissionais desta família ocupacional cri...
196,862160,R. Manual,Operador de abastecimento de combustível de ae...,"Captam águas subterrâneas e superficiais, regi..."
197,913125,R. Manual,Vulcanizador de correias transportadoras,Planejam e realizam a manutenção de motores e ...
198,951315,Manual,Monitor de sistemas eletrônicos de segurança i...,"Instalam elevadores, escadas rolantes, portas ..."
199,951320,Manual,Monitor de sistemas eletrônicos de segurança e...,"Instalam elevadores, escadas rolantes, portas ..."

In [436]:
lista_não_tem_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ocupacao   200 non-null    str
 1   tarefa     200 non-null    str
 2   titulo     200 non-null    str
 3   descricao  200 non-null    str
dtypes: str(4)
memory usage: 104.8 KB

In [437]:
# Preencher coluna tarefa em `dados` usando `dados_nossos`
# Regra: 1) match exato ocupacao == CODIGO; 2) fallback por grupo (4 primeiros dígitos)

dados_nossos_aux = dados_nossos.copy()
dados_nossos_aux['CODIGO'] = dados_nossos_aux['CODIGO'].astype(str).str.zfill(6)
dados_nossos_aux['Grupo'] = dados_nossos_aux['Grupo'].astype(str).str.zfill(4)

dados['ocupacao'] = dados['ocupacao'].astype(str).str.zfill(6)

# 1) Match exato por código
tarefa_por_codigo = (
    dados_nossos_aux
    .dropna(subset=['Tarefa'])
    .drop_duplicates(subset=['CODIGO'])
    .set_index('CODIGO')['Tarefa']
)

dados['tarefa'] = dados['ocupacao'].map(tarefa_por_codigo)

# 2) Fallback por grupo (4 dígitos)
tarefa_por_grupo = (
    dados_nossos_aux
    .dropna(subset=['Tarefa'])
    .groupby('Grupo')['Tarefa']
    .agg(lambda s: s.mode().iat[0] if not s.mode().empty else s.iloc[0])
)

mask_faltando = dados['tarefa'].isna()
dados.loc[mask_faltando, 'tarefa'] = (
    dados.loc[mask_faltando, 'ocupacao'].str[:4].map(tarefa_por_grupo)
)

print('Coluna tarefa preenchida em `dados`.')
print('Total linhas:', len(dados))
print('Tarefas preenchidas:', dados['tarefa'].notna().sum())
print('Tarefas vazias:', dados['tarefa'].isna().sum())
dados[['ocupacao', 'titulo', 'tarefa']].head(15)

Coluna tarefa preenchida em `dados`.
Total linhas: 2610
Tarefas preenchidas: 2553
Tarefas vazias: 57

   ocupacao                                             titulo    tarefa
0    010105  0101-05 Oficial General da Aeronáutica - Briga...  Abstrata
1    010110  0101-10 Oficial General do Exército - General-...  Abstrata
2    010115  0101-15 Oficial General da Marinha - Almirante...  Abstrata
3    010205  0102-05 Oficial da Aeronáutica - Capitão; Coro...  Abstrata
4    010210  0102-10 Oficial do Exército - Capitão; Coronel...  Abstrata
5    010215  0102-15 Oficial da Marinha - Capitão-de-corvet...  Abstrata
6    010305  0103-05 Praça da aeronáutica - Cabo; Primeiro-...  Abstrata
7    010310  0103-10 Praça do exército - Cabo; Primeiro-sar...  Abstrata
8    010315  0103-15 Praça da marinha - Cabo; Marinheiro; P...  Abstrata
9    020105                 0201-05 Coronel da Polícia Militar  Abstrata
10   020110         0201-10 Tenente-Coronel da Polícia Militar  Abstrata
11   020115                   0201-15 Major da Polícia Militar  Abstrata
12   020205                 0202-05 Capitão da Polícia Militar  Abstrata
13   020305        0203-05 Primeiro Tenente de Polícia Militar  Abstrata
14   020310         0203-10 Segundo Tenente de Polícia Militar  Abstrata

In [438]:
dados.describe()

,titulo,descricao,4n,ocupacao,tarefa
count,2610,2610,2486,2610,2553
unique,2610,626,606,2610,6
top,0101-05 Oficial General da Aeronáutica - Briga...,Realizam consultas e atendimentos médicos; tra...,2231,010105,Abstrata
freq,1,57,57,1,964

In [439]:
dados

,titulo,descricao,4n,ocupacao,tarefa
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",0101,010105,Abstrata
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",0101,010110,Abstrata
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",0101,010115,Abstrata
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,0102,010205,Abstrata
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,0102,010210,Abstrata
...,...,...,...,...,...
2607,225335 Médico patologista clínico / medicina l...,Realizam procedimentos de diagnóstico e terapê...,NaN,225335,Abstrata
2608,225340 Médico hemoterapeuta,Realizam procedimentos de diagnóstico e terapê...,NaN,225340,Abstrato
2609,225345 Médico hiperbarista,Realizam procedimentos de diagnóstico e terapê...,NaN,225345,Abstrato
2610,225350 Médico neurofisiologista clínico,Realizam procedimentos de diagnóstico e terapê...,NaN,225350,Abstrato
2611,225355 Médico radiologista intervencionista,Realizam procedimentos de diagnóstico e terapê...,NaN,225355,Abstrato

In [440]:
dados = pd.concat([dados, lista_não_tem_df], ignore_index=True)
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 2810 entries, 0 to 2809
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2810 non-null   str
 1   descricao  2810 non-null   str
 2   4n         2486 non-null   str
 3   ocupacao   2810 non-null   str
 4   tarefa     2753 non-null   str
dtypes: str(5)
memory usage: 1.7 MB

In [441]:
dados.dropna(subset=['tarefa'], inplace=True)
dados.info()

<class 'pandas.DataFrame'>
Index: 2753 entries, 0 to 2809
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2753 non-null   str
 1   descricao  2753 non-null   str
 2   4n         2429 non-null   str
 3   ocupacao   2753 non-null   str
 4   tarefa     2753 non-null   str
dtypes: str(5)
memory usage: 1.7 MB

In [442]:
dados.drop(columns=['4n'], inplace=True)

In [443]:
dados.info()

<class 'pandas.DataFrame'>
Index: 2753 entries, 0 to 2809
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2753 non-null   str
 1   descricao  2753 non-null   str
 2   ocupacao   2753 non-null   str
 3   tarefa     2753 non-null   str
dtypes: str(4)
memory usage: 1.7 MB

In [444]:
dados

,titulo,descricao,ocupacao,tarefa
0,0101-05 Oficial General da Aeronáutica - Briga...,"As funções deste grupo consistem em manter, cu...",010105,Abstrata
1,0101-10 Oficial General do Exército - General-...,"As funções deste grupo consistem em manter, cu...",010110,Abstrata
2,0101-15 Oficial General da Marinha - Almirante...,"As funções deste grupo consistem em manter, cu...",010115,Abstrata
3,0102-05 Oficial da Aeronáutica - Capitão; Coro...,Estão compreendidas nesta família ocupacional ...,010205,Abstrata
4,0102-10 Oficial do Exército - Capitão; Coronel...,Estão compreendidas nesta família ocupacional ...,010210,Abstrata
...,...,...,...,...
2805,Artesão rendeiro,Os profissionais desta família ocupacional cri...,791160,R. Manual
2806,Operador de abastecimento de combustível de ae...,"Captam águas subterrâneas e superficiais, regi...",862160,R. Manual
2807,Vulcanizador de correias transportadoras,Planejam e realizam a manutenção de motores e ...,913125,R. Manual
2808,Monitor de sistemas eletrônicos de segurança i...,"Instalam elevadores, escadas rolantes, portas ...",951315,Manual
2809,Monitor de sistemas eletrônicos de segurança e...,"Instalam elevadores, escadas rolantes, portas ...",951320,Manual

In [ ]:
# Substituir 'Abstrato' por 'Abstrata' na coluna tarefa
dados.loc[dados['tarefa'] == 'Abstrato', 'tarefa'] = 'Abstrata'

Valores 'Abstrato' substituídos por 'Abstrata'
Total de 'Abstrata': 1148

In [457]:
dados.value_counts('tarefa').head(20)

tarefa
Abstrata                               1148
Manual                                  684
R. Manual                               659
R. Cognitiva                            250
R. Cognitiva // R. Manual // Manual       1
Name: count, dtype: int64

In [451]:
dados.drop(index=dados[dados['tarefa'] == 'Manual/ R.Cognitiva/ R. Manual'].index, inplace=True)

In [459]:
dados.drop(index=dados[dados['tarefa'] == 'R. Cognitiva // R. Manual // Manual'].index, inplace=True)

In [460]:
dados.value_counts('tarefa').head(20)

tarefa
Abstrata        1148
Manual           684
R. Manual        659
R. Cognitiva     250
Name: count, dtype: int64

In [467]:
dados.to_csv('dados_tratados.csv', index=False)

In [465]:
dados.drop_duplicates(inplace=True)

In [466]:
dados.info()

<class 'pandas.DataFrame'>
Index: 2741 entries, 0 to 2809
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   titulo     2741 non-null   str
 1   descricao  2741 non-null   str
 2   ocupacao   2741 non-null   str
 3   tarefa     2741 non-null   str
dtypes: str(4)
memory usage: 1.6 MB